use defaultdb;
CREATE TABLE Accounts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Devices (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    device_id INT,
    Name NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sensors (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DeviceID INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Unit NVARCHAR(20) NULL,
    FOREIGN KEY (DeviceID) REFERENCES Devices(ID) ON DELETE CASCADE
);

CREATE TABLE SensorData (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SensorID INT NOT NULL,
    Value FLOAT NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SensorID) REFERENCES Sensors(ID) ON DELETE CASCADE
);