use defaultdb;

CREATE TABLE Devices (
    ID INT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Status NVARCHAR(20),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sensors (
    ID INT PRIMARY KEY,
    DeviceID INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Unit NVARCHAR(20) NULL,
    FOREIGN KEY (DeviceID) REFERENCES Devices(ID) ON DELETE CASCADE
);

CREATE TABLE SensorData (
    ID INT PRIMARY KEY,
    SensorID INT NOT NULL,
    Value FLOAT NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SensorID) REFERENCES Sensors(ID) ON DELETE CASCADE
);